##################################################################################
# Environment-specific Helm overrides managed by yarn environment:init
# Unmanaged keys are preserved when this file is updated.
##################################################################################
hostname: migration-staging.opencrvs.dev
platform:
  imagePullPolicy: Always
env:
  APN_SERVICE_URL: apm-server.opencrvs-deps-qa.svc.cluster.local
  APN_ENVIRONMENT: migration-staging

otel:
  enabled: true
  deployment_environment: migration-staging
  exporter_otlp_endpoint: "http://opentelemetry-collector.opencrvs-deps-qa.svc.cluster.local:4317"

countryconfig:
  env:
    OPENID_PROVIDER_CLAIMS: name,family_name,given_name,middle_name,birthdate,address
    OPENID_PROVIDER_CLIENT_ID: mock-client_id
    ESIGNET_REDIRECT_URL: https://esignet-mock.migration-staging.opencrvs.dev/authorize
    MOSIP_API_USERINFO_URL: https://mosip-api.migration-staging.opencrvs.dev/esignet/get-oidp-user-info
    VERIFIABLE_CREDENTIALS_SDJWT_ISSUE_URL: https://proxy.issuer.opencrvs.dev/openid4vc/sdjwt/issue
    VERIFIABLE_CREDENTIALS_RAW_JWT_SIGN_URL: https://proxy.issuer.opencrvs.dev/raw/jwt/sign
    ENVIRONMENT_NAME: migration-staging
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_DATABASE_URL
    mosip-integration-secret:
      - OPENCRVS_MOSIP_CLIENT_ID:MOSIP_INTEGRATION_CLIENT_ID
      - OPENCRVS_MOSIP_CLIENT_SECRET:MOSIP_INTEGRATION_CLIENT_SECRET
postgres_on_deploy:
  secrets:
    reference-data-db-secret:
      - REFERENCE_DATA_POSTGRES_USER
      - REFERENCE_DATA_POSTGRES_PASSWORD
      - REFERENCE_DATA_EDITOR_USER
      - REFERENCE_DATA_EDITOR_PASSWORD
