chart_dev_mode: false

ingress:
  tls_resolver: letsencrypt

hpa:
  enabled: false

env:
  APN_SERVICE_URL: "http://apm-server.opencrvs-deps-demo.svc.cluster.local:8200"

hostname: test-k8s.opencrvs.dev
elasticsearch:
  auth_mode: auto
  port: 9200
  host: elasticsearch.opencrvs-deps-demo.svc.cluster.local

minio:
  auth_mode: use_secret
  host: minio-0.minio.opencrvs-deps-demo.svc.cluster.local
  external_hostname: minio.test-k8s.opencrvs.dev

redis:
  auth_mode: disabled
  host: redis-0.redis.opencrvs-deps-demo.svc.cluster.local

postgres:
  auth_mode: auto
  host: postgres-0.postgres.opencrvs-deps-demo.svc.cluster.local

resources:
  memoryRequest: "256Mi"
  cpuRequest: "200m"
  memoryLimit: "2Gi"
  cpuLimit: "1"

image:
  tag: 0f10027

dashboards:
  use_default_credentials: false

countryconfig:
  image:
    # Replace countryconfig with farajaland to test data
    name: opencrvs/ocrvs-farajaland
    # name: opencrvs/ocrvs-countryconfig
    tag: 3314a9a
    # tag: ec53c12
    # tag: v1.8.1

  env:
    OPENID_PROVIDER_CLAIMS: name,family_name,given_name,middle_name,birthdate,address
    OPENID_PROVIDER_CLIENT_ID: mock-client_id
    V2_EVENTS: "true"
    FIXME: In general these values should be passed externally using `--set key=value`
    ESIGNET_REDIRECT_URL: https://esignet-mock.test-k8s.opencrvs.dev/authorize
    MOSIP_API_USERINFO_URL: https://mosip-api.test-k8s.opencrvs.dev/esignet/get-oidp-user-info

data_seed:
  env:
    SUPER_USER_PASSWORD: "password"
    ACTIVATE_USERS: "true"
