##################################################################################
# Environment-specific Helm overrides managed by yarn environment:init
# Unmanaged keys are preserved when this file is updated.
##################################################################################
hostname: migration-production.opencrvs.dev
monitoring:
  enabled: false

elasticsearch:
  host_data_path: /data/migration-production/elasticsearch

minio:
  host_data_path: /data/migration-production/minio

mongodb:
  host_data_path: /data/migration-production/mongodb

postgres:
  host_data_path: /data/migration-production/postgres

influxdb:
  host_data_path: /data/migration-production/influxdb

# FIXME: Keep this value till first official v2.1.0 release.
utilities:
  image:
    tag: 35b1e0f
