chart_dev_mode: false
hostname: test-stg-k8s.opencrvs.dev
storage_type: host_path
node_selector:
  role: data2

ingress:
  tls_resolver: letsencrypt

redis:
  auth_mode: disabled

minio:
  use_default_credentials: false

elasticsearch:
  use_default_credentials: false
  node_selector:
    role: data1

postgres:
  use_default_credentials: false

monitoring:
  enabled: false

backup:
  enabled: true
  backup_server_dir: /home/backup/demo-staging

restore:
  enabled: true
  backup_server_dir: /home/backup/demo

priority_class:
  enabled: true
