- name: Download Helm apt repository signing key
  ansible.builtin.get_url:
    url: https://packages.buildkite.com/helm-linux/helm-debian/gpgkey
    dest: /tmp/helm.gpg
    mode: "0644"

- name: Dearmor Helm apt repository signing key
  ansible.builtin.command:
    cmd: gpg --dearmor --yes --output /etc/apt/keyrings/helm.gpg /tmp/helm.gpg
  become: yes
  changed_when: false

- name: Add Helm apt repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/helm.gpg] https://packages.buildkite.com/helm-linux/helm-debian/any/ any main
    filename: helm-stable-debian
    state: present
    update_cache: yes
  become: yes

- name: Remove legacy Helm binary installed from tarball
  ansible.builtin.file:
    path: /usr/local/bin/helm
    state: absent
  become: yes

- name: Install Helm
  ansible.builtin.apt:
    name: "helm={{ helm_version }}"
    state: present
    allow_downgrade: yes
  become: yes

- name: Check installed Helm diff plugin version
  ansible.builtin.command: helm diff version
  register: installed_helm_diff_plugin_version
  changed_when: false
  failed_when: false

- name: Remove mismatched Helm diff plugin
  ansible.builtin.command: helm plugin remove diff
  when:
    - installed_helm_diff_plugin_version.rc == 0
    - helm_diff_plugin_version not in installed_helm_diff_plugin_version.stdout

- name: Install Helm diff plugin
  ansible.builtin.command: helm plugin install https://github.com/databus23/helm-diff --version {{ helm_diff_plugin_version }}
  when: >
    installed_helm_diff_plugin_version.rc != 0 or
    helm_diff_plugin_version not in installed_helm_diff_plugin_version.stdout
