# TODO: Make Kubernetes components
- name: Download manifest for metrics server
  get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: /tmp/metrics-server.yaml
    mode: '0644'

- name: Install metrics server on control plane
  shell: |
    kubectl apply -f /tmp/metrics-server.yaml
  become: yes
  environment:
    KUBECONFIG: /home/{{ provisioning_user }}/.kube/config

- name: Add --kubelet-insecure-tls to metrics-server
  shell: |
    kubectl -n kube-system patch deployment metrics-server \
    --type='json' \
    -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]'
  environment:
    KUBECONFIG: /home/{{ provisioning_user }}/.kube/config

- name: Wait for metrics server to be ready
  shell: |
    kubectl wait --for=condition=ready pod -l k8s-app=metrics-server -n kube-system --timeout=30s
  become: yes
  retries: 5
  delay: 30
  environment:
    KUBECONFIG: /home/{{ provisioning_user }}/.kube/config

- name: Verify metrics server installation
  shell: |
     kubectl get deployment metrics-server -n kube-system
  become: yes
  register: metrics_server_status
  environment:
    KUBECONFIG: /home/{{ provisioning_user }}/.kube/config
- name: Display metrics server status
  debug:
    msg: "Metrics server is installed and running: {{ metrics_server_status.stdout }}"
  when: metrics_server_status.rc == 0

- name: Clean up temporary files
  file:
    path: /tmp/metrics-server.yaml
    state: absent