# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
---
- hosts: backup
  become: yes
  become_method: sudo
  tags: backup
  tasks:
    - name: Install pgBackRest
      include_tasks: tasks/backups/install-pgbackrest.yml
    - name: Create backup user
      include_tasks: tasks/backups/create-backup-user.yml
    - name: Configure crontab
      include_tasks: tasks/backups/crontab-rotate-backup.yml
    - name: Setup server login emails
      include_tasks: tasks/backups/setup-email-alert.yml
    - name: Store disk encryption key
      include_tasks: tasks/backups/store-disk-encryption-key.yml