name: 06. Backup
run-name: "Backup ${{ inputs.environment }} environment"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        default: "e2e"
        type: choice
        options:
          - e2e
          - migration-production
          - migration-staging
          - qa
  workflow_call:
    inputs:
      environment:
        type: string
        required: true

env:
  namespace: opencrvs-deps-${{ inputs.environment }}

jobs:
  approve:
    runs-on: ubuntu-26.04
    environment: ${{ inputs.environment }}
    timeout-minutes: 60
    steps:
      - name: Waiting for manual approval
        if: ${{ (vars.APPROVAL_REQUIRED || 'false') == 'true' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.GH_APPROVERS }}
          minimum-approvals: ${{ inputs.job-name == 'data-cleanup' && 3 || 1 }}
          issue-title: "Run ${{ inputs.job-name }} job on ${{ inputs.environment }} environment"
          issue-body: >
            Please approve or deny job ${{ inputs.job-name }} on ${{ inputs.environment }} environment
            initiated from GitHub Actions by @${{ github.actor }}.
          exclude-workflow-initiator-as-approver: false
  prepare:
    needs: approve
    environment: ${{ inputs.environment }}
    outputs:
      job-names: ${{ steps.profile.outputs.job-names }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    steps:
      - name: Get job names
        id: profile
        env:
          BACKUP_ENVIRONMENT_MODE: ${{ vars.BACKUP_ENVIRONMENT_MODE || '' }}
        run: |
          if [ "${BACKUP_ENVIRONMENT_MODE}" = "dump" ]; then
            job_names='["minio-backup","postgres-backup"]'
          elif [ "${BACKUP_ENVIRONMENT_MODE}" = "differential" ]; then
            job_names='["minio-backup","postgres-backup-full"]'
          else
            echo "::error::Backup is not configured for this environment. Unsupported backup mode: ${BACKUP_ENVIRONMENT_MODE}"
            exit 1
          fi
          echo "job-names=${job_names}" >> "$GITHUB_OUTPUT"
  job-run:
    name: ${{ matrix.job-name }}
    needs: prepare
    environment: ${{ inputs.environment }}
    runs-on:
      - self-hosted
      - k8s
      - ${{ inputs.environment }}
    strategy:
      max-parallel: 1
      fail-fast: true
      matrix:
        job-name: ${{ fromJSON(needs.prepare.outputs.job-names) }}
    steps:
      - name: Create job ${{ matrix.job-name }} from cronjob
        run: |
          kubectl delete job -n ${namespace} --ignore-not-found=true ${{ matrix.job-name }}
          kubectl create job -n ${namespace} --from=cronjob/${{ matrix.job-name }} ${{ matrix.job-name }};
          echo "✅ ${{ matrix.job-name }} job created successfully"
      - name: Checking ${{ matrix.job-name }} job status
        run: |
          while true; do
            kubectl wait --for=condition=ready pod -ljob-name=${{ matrix.job-name }} --timeout=300s -n ${namespace} && \
            kubectl logs job/${{ matrix.job-name }} --all-containers -f -n ${namespace} && \
            touch /tmp/logs_stramed-${namespace}-${{ matrix.job-name }}.txt || break; 
            sleep 1; done &
          echo "---------------------- Waiting for job completion ----------------------"
          kubectl wait --for=condition=complete job/${{ matrix.job-name }} -n ${namespace} --timeout=600s; status=$? || true
          [ $status -ne 0 ] && kubectl get pods -n ${namespace} --show-labels && kubectl describe pod -ljob-name=${job_name} -n ${namespace};
          [ ! -f /tmp/logs_stramed-${namespace}-${{ matrix.job-name }}.txt ] && kubectl logs job/${{ matrix.job-name }} --all-containers -n ${namespace} || \
            rm -vf /tmp/logs_stramed-${namespace}-${{ matrix.job-name }}.txt
          kill %1 2>/dev/null && echo "Stopped log streaming" || true
          exit $status
